### ISSUE TITLE
Allow Cors

### ISSUE THREAD

**Issue by heyoung** [kieranwadia/upworkjob#4]
All POST requests from the browser only are failing, I think the backend needs to enable/allow cors: https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-5.0

Before all post requests the browser automatically sends an OPTIONS request but the server is returning a 404.

Request:
OPTIONS /api/passcode HTTP/1.1
Host: s850604947.websitehome.co.uk
Connection: keep-alive
Accept: */*
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Origin: http://localhost:3000
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
Sec-Fetch-Mode: cors
Referer: http://localhost:3000/
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8

Response:
HTTP/1.1 404 Not Found
Content-Length: 0
Connection: keep-alive
Keep-Alive: timeout=15
Server: Kestrel
X-Powered-By: ASP.NET
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Date: Sun, 07 Mar 2021 16:30:53 GMT

**Comment by kieranwadia** [comment]
@heyoung, Better now?

**Comment by kieranwadia** [comment]
Actually, I don't think CORS is the issue. Looking at logs, I see this log line (I've XX'd out some personal info):
```
2021-03-07 16:15:18,451 INFO  [75] (Service.Controllers.LoginController) - 90.193.92.XX(Id:0HM71FT5V3MXX) sent HttpPost with NoAuth with PhoneNumber 07777777777
2021-03-07 16:15:18,459 INFO  [75] (Service.Controllers.LoginController) - Beginning request to send message (Passcode: 5555) to 07777777777 (intl: +447777777777)
2021-03-07 16:15:18,460 INFO  [75] (Service.Controllers.LoginController) - Checking price of sending message to +447777777777
2021-03-07 16:16:21,579 ERROR [79] (Service.Controllers.LoginController) - System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Service.Sms.MessagingService.GetPriceInPence(String number, String message) in C:\Code\visualbirthplan\VisualBirthPlan\Service\Sms\SmsService.cs:line 101
   at Service.Sms.MessagingService.SendMessage(String localNumber, String message) in C:\Code\visualbirthplan\VisualBirthPlan\Service\Sms\SmsService.cs:line 71
2021-03-07 16:16:21,977 ERROR [79] (Service.Logic.UserManagement) - Passcode failed to send because: Unknown
2021-03-07 16:16:21,984 WARN  [79] (Service.Logic.UserManagement) - SendPasscode took 63527ms
```

For now, you can login using the passcode `5555`, and it should let you through (even if that initial `POST` fails). I'll try this issue though, so you don't get that failure.

**Comment by heyoung** [comment]
Still getting a `404` posting `5555`. I get a `200` when I post it through Postman, it just takes a little time. Sending an OPTIONS request through postman I get the same `404` response as when I post through the browser.

**Comment by kieranwadia** [comment]
Okay, should be good now. I'll added the policy, but forgot to add it site-wide

**Comment by heyoung** [comment]
Still getting an error on this: 
`Access to fetch at 'http://s850604947.websitehome.co.uk/api/passcode' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value`

**Comment by kieranwadia** [comment]
Should be better now:
![image](https://user-images.githubusercontent.com/20935522/111005799-6564ee80-8383-11eb-9479-9bae0d3e1857.png)

**Comment by heyoung** [comment]
Yup that looks good. Couple of point on the /passcode route:
1. The UI supports international dialling codes so would be of the form +44123456. Assuming that is ok?
2. The request returns a 200 but it takes around 1min to complete and I don't get any texts

**Comment by kieranwadia** [comment]
At the moment it expects the 079... format only, but I'll update it to
accept international. Texts are broken, but the passcode is hard coded to
5555.

**Comment by heyoung** [comment]
Is this response expected when using 5555:
```
authId: null
failureReason: "Try refreshing the page and resending phone number"
requestPasscodeRetry: false
requestPhoneNumberResend: true
success: false
```

**Comment by kieranwadia** [comment]
I don't think so. Not sure what's going on there. Maybe the issue with
texts not sending is causing other issues (i.e. the passcode not being
created).

Will need to take a look tonight.

**Comment by kieranwadia** [comment]
It was indeed an issue with the passcode not being sent.

I've changed to store the default passcode (5555) even if the text message doesn't go through successfully.

**Comment by kieranwadia** [comment]
I've switched off sending the text message completely, so POST /api/passcode will return you a 200 back immediately. The default passcode will be 5555 (and you definitely won't get a text message)

**Comment by kieranwadia** [comment]
:(

It seems that CORS and Cookies doesn't play very well (and Cookies were supposed to provide an AuthId value to validate the users so the server knows what info to return).

I've updated the server code to allow a querystring parameter (if there's no cookie). So URLs that need you to be logged in for, can also be called like: `/api/birthplan?authId=4896ac94-101f-4ef8-8b0d-21ca4e94bd6e` (where the authId comes from the `.authId` property on the result of calling POST to `/api/login`)

Not ideal, but I'm not having much luck getting CORS+Cookies to work. Since CORS is only an issue during Dev, I'm hoping the (piss-poor security of a) querystring won't be necessary for Prod rollout. Can you handle this behaviour?

**Comment by heyoung** [comment]
Yeh I can use that for testing.
